name: Daily Commit Bot

on:
  schedule:
    - cron: "17 7 * * *"   # Runs every day at 00:00 UTC
  workflow_dispatch:       # Allows manual trigger too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last update: $(date)" > update.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add update.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
